spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  file:
    name: logs/spring-outs-05-2023.log
  logback:
    rollingpolicy:
      file-name-pattern: spring-outs-05-2023.%d{yyyy-MM-dd}.%i.gz
      max-file-size: 10MB
  level:
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  health:
    defaults:
      enabled: true