DROP TABLE IF EXISTS authors;
CREATE TABLE authors
(
    id           int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    authors_name VARCHAR(255),
    author_year  int8 NOT NULL,
    CONSTRAINT pk_authors PRIMARY KEY (id)
);


DROP TABLE IF EXISTS genres;
CREATE TABLE genres
(
    id          int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    genres_name VARCHAR(255),
    CONSTRAINT pk_genres PRIMARY KEY (id)
);

DROP TABLE IF EXISTS books;
CREATE TABLE books
(
    id        int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    book_name VARCHAR(255),
    book_year int4,
    author_id int8 NOT NULL,
    genre_id  int8 NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id)
);

ALTER TABLE books
    ADD CONSTRAINT fk_authors FOREIGN KEY (author_id) REFERENCES authors (id);
ALTER TABLE books
    ADD CONSTRAINT fk_genres FOREIGN KEY (genre_id) REFERENCES genres (id);