spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false

  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true

  data:
    mongodb:
      database: library
      port: 27017
      host: localhost
    main:
      allow-circular-references: true
    batch:
      job:
        enabled: true
    shell:
      interactive:
        enabled: true
      noninteractive:
        enabled: false
      command:
        version:
          enabled: false